// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.15.5
// source: calculator/calpb/cal.proto

package calpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstNum  int32 `protobuf:"varint,1,opt,name=first_num,json=firstNum,proto3" json:"first_num,omitempty"`
	SecondNum int32 `protobuf:"varint,2,opt,name=second_num,json=secondNum,proto3" json:"second_num,omitempty"`
}

func (x *CalRequest) Reset() {
	*x = CalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculator_calpb_cal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalRequest) ProtoMessage() {}

func (x *CalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_calpb_cal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalRequest.ProtoReflect.Descriptor instead.
func (*CalRequest) Descriptor() ([]byte, []int) {
	return file_calculator_calpb_cal_proto_rawDescGZIP(), []int{0}
}

func (x *CalRequest) GetFirstNum() int32 {
	if x != nil {
		return x.FirstNum
	}
	return 0
}

func (x *CalRequest) GetSecondNum() int32 {
	if x != nil {
		return x.SecondNum
	}
	return 0
}

type CalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CalResponse) Reset() {
	*x = CalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculator_calpb_cal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalResponse) ProtoMessage() {}

func (x *CalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_calpb_cal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalResponse.ProtoReflect.Descriptor instead.
func (*CalResponse) Descriptor() ([]byte, []int) {
	return file_calculator_calpb_cal_proto_rawDescGZIP(), []int{1}
}

func (x *CalResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type PrimeNoDecompositionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *PrimeNoDecompositionRequest) Reset() {
	*x = PrimeNoDecompositionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculator_calpb_cal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimeNoDecompositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeNoDecompositionRequest) ProtoMessage() {}

func (x *PrimeNoDecompositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_calpb_cal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeNoDecompositionRequest.ProtoReflect.Descriptor instead.
func (*PrimeNoDecompositionRequest) Descriptor() ([]byte, []int) {
	return file_calculator_calpb_cal_proto_rawDescGZIP(), []int{2}
}

func (x *PrimeNoDecompositionRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type PrimeNoDecompositionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *PrimeNoDecompositionResponse) Reset() {
	*x = PrimeNoDecompositionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculator_calpb_cal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimeNoDecompositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeNoDecompositionResponse) ProtoMessage() {}

func (x *PrimeNoDecompositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_calpb_cal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeNoDecompositionResponse.ProtoReflect.Descriptor instead.
func (*PrimeNoDecompositionResponse) Descriptor() ([]byte, []int) {
	return file_calculator_calpb_cal_proto_rawDescGZIP(), []int{3}
}

func (x *PrimeNoDecompositionResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type CalAverageofNumbersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *CalAverageofNumbersRequest) Reset() {
	*x = CalAverageofNumbersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculator_calpb_cal_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalAverageofNumbersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalAverageofNumbersRequest) ProtoMessage() {}

func (x *CalAverageofNumbersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_calpb_cal_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalAverageofNumbersRequest.ProtoReflect.Descriptor instead.
func (*CalAverageofNumbersRequest) Descriptor() ([]byte, []int) {
	return file_calculator_calpb_cal_proto_rawDescGZIP(), []int{4}
}

func (x *CalAverageofNumbersRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type CalAverageofNumbersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CalAverageofNumbersResponse) Reset() {
	*x = CalAverageofNumbersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculator_calpb_cal_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalAverageofNumbersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalAverageofNumbersResponse) ProtoMessage() {}

func (x *CalAverageofNumbersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_calpb_cal_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalAverageofNumbersResponse.ProtoReflect.Descriptor instead.
func (*CalAverageofNumbersResponse) Descriptor() ([]byte, []int) {
	return file_calculator_calpb_cal_proto_rawDescGZIP(), []int{5}
}

func (x *CalAverageofNumbersResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_calculator_calpb_cal_proto protoreflect.FileDescriptor

var file_calculator_calpb_cal_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x63, 0x61, 0x6c,
	0x70, 0x62, 0x2f, 0x63, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x48, 0x0a, 0x0a, 0x63, 0x61, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f,
	0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x4e, 0x75, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x5f, 0x6e, 0x75,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x4e,
	0x75, 0x6d, 0x22, 0x25, 0x0a, 0x0b, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x35, 0x0a, 0x1b, 0x50, 0x72, 0x69,
	0x6d, 0x65, 0x4e, 0x6f, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x22, 0x36, 0x0a, 0x1c, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x4e, 0x6f, 0x44, 0x65, 0x63, 0x6f, 0x6d,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x34, 0x0a, 0x1a, 0x43, 0x61, 0x6c, 0x41,
	0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x6f, 0x66, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x35,
	0x0a, 0x1b, 0x43, 0x61, 0x6c, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x6f, 0x66, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0xa9, 0x02, 0x0a, 0x0a, 0x43, 0x61, 0x6c, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x0b, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x16, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x63, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6d, 0x0a, 0x14, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x4e,
	0x6f, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27,
	0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x72, 0x69, 0x6d,
	0x65, 0x4e, 0x6f, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x4e, 0x6f, 0x44, 0x65, 0x63, 0x6f,
	0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x6a, 0x0a, 0x13, 0x43, 0x61, 0x6c, 0x41, 0x76, 0x65, 0x72,
	0x61, 0x67, 0x65, 0x6f, 0x66, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x26, 0x2e, 0x63,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x61, 0x6c, 0x41, 0x76, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x6f, 0x66, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x43, 0x61, 0x6c, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x6f, 0x66, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28,
	0x01, 0x42, 0x12, 0x5a, 0x10, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f,
	0x63, 0x61, 0x6c, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_calculator_calpb_cal_proto_rawDescOnce sync.Once
	file_calculator_calpb_cal_proto_rawDescData = file_calculator_calpb_cal_proto_rawDesc
)

func file_calculator_calpb_cal_proto_rawDescGZIP() []byte {
	file_calculator_calpb_cal_proto_rawDescOnce.Do(func() {
		file_calculator_calpb_cal_proto_rawDescData = protoimpl.X.CompressGZIP(file_calculator_calpb_cal_proto_rawDescData)
	})
	return file_calculator_calpb_cal_proto_rawDescData
}

var file_calculator_calpb_cal_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_calculator_calpb_cal_proto_goTypes = []interface{}{
	(*CalRequest)(nil),                   // 0: calculator.calRequest
	(*CalResponse)(nil),                  // 1: calculator.calResponse
	(*PrimeNoDecompositionRequest)(nil),  // 2: calculator.PrimeNoDecompositionRequest
	(*PrimeNoDecompositionResponse)(nil), // 3: calculator.PrimeNoDecompositionResponse
	(*CalAverageofNumbersRequest)(nil),   // 4: calculator.CalAverageofNumbersRequest
	(*CalAverageofNumbersResponse)(nil),  // 5: calculator.CalAverageofNumbersResponse
}
var file_calculator_calpb_cal_proto_depIdxs = []int32{
	0, // 0: calculator.CalService.Calculation:input_type -> calculator.calRequest
	2, // 1: calculator.CalService.PrimeNoDecomposition:input_type -> calculator.PrimeNoDecompositionRequest
	4, // 2: calculator.CalService.CalAverageofNumbers:input_type -> calculator.CalAverageofNumbersRequest
	1, // 3: calculator.CalService.Calculation:output_type -> calculator.calResponse
	3, // 4: calculator.CalService.PrimeNoDecomposition:output_type -> calculator.PrimeNoDecompositionResponse
	5, // 5: calculator.CalService.CalAverageofNumbers:output_type -> calculator.CalAverageofNumbersResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calculator_calpb_cal_proto_init() }
func file_calculator_calpb_cal_proto_init() {
	if File_calculator_calpb_cal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_calculator_calpb_cal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculator_calpb_cal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculator_calpb_cal_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimeNoDecompositionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculator_calpb_cal_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimeNoDecompositionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculator_calpb_cal_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalAverageofNumbersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculator_calpb_cal_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalAverageofNumbersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_calculator_calpb_cal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculator_calpb_cal_proto_goTypes,
		DependencyIndexes: file_calculator_calpb_cal_proto_depIdxs,
		MessageInfos:      file_calculator_calpb_cal_proto_msgTypes,
	}.Build()
	File_calculator_calpb_cal_proto = out.File
	file_calculator_calpb_cal_proto_rawDesc = nil
	file_calculator_calpb_cal_proto_goTypes = nil
	file_calculator_calpb_cal_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CalServiceClient is the client API for CalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalServiceClient interface {
	//Unary
	Calculation(ctx context.Context, in *CalRequest, opts ...grpc.CallOption) (*CalResponse, error)
	//Server Streaming
	PrimeNoDecomposition(ctx context.Context, in *PrimeNoDecompositionRequest, opts ...grpc.CallOption) (CalService_PrimeNoDecompositionClient, error)
	//Client streaming
	CalAverageofNumbers(ctx context.Context, opts ...grpc.CallOption) (CalService_CalAverageofNumbersClient, error)
}

type calServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalServiceClient(cc grpc.ClientConnInterface) CalServiceClient {
	return &calServiceClient{cc}
}

func (c *calServiceClient) Calculation(ctx context.Context, in *CalRequest, opts ...grpc.CallOption) (*CalResponse, error) {
	out := new(CalResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalService/Calculation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calServiceClient) PrimeNoDecomposition(ctx context.Context, in *PrimeNoDecompositionRequest, opts ...grpc.CallOption) (CalService_PrimeNoDecompositionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalService_serviceDesc.Streams[0], "/calculator.CalService/PrimeNoDecomposition", opts...)
	if err != nil {
		return nil, err
	}
	x := &calServicePrimeNoDecompositionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalService_PrimeNoDecompositionClient interface {
	Recv() (*PrimeNoDecompositionResponse, error)
	grpc.ClientStream
}

type calServicePrimeNoDecompositionClient struct {
	grpc.ClientStream
}

func (x *calServicePrimeNoDecompositionClient) Recv() (*PrimeNoDecompositionResponse, error) {
	m := new(PrimeNoDecompositionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calServiceClient) CalAverageofNumbers(ctx context.Context, opts ...grpc.CallOption) (CalService_CalAverageofNumbersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalService_serviceDesc.Streams[1], "/calculator.CalService/CalAverageofNumbers", opts...)
	if err != nil {
		return nil, err
	}
	x := &calServiceCalAverageofNumbersClient{stream}
	return x, nil
}

type CalService_CalAverageofNumbersClient interface {
	Send(*CalAverageofNumbersRequest) error
	CloseAndRecv() (*CalAverageofNumbersResponse, error)
	grpc.ClientStream
}

type calServiceCalAverageofNumbersClient struct {
	grpc.ClientStream
}

func (x *calServiceCalAverageofNumbersClient) Send(m *CalAverageofNumbersRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calServiceCalAverageofNumbersClient) CloseAndRecv() (*CalAverageofNumbersResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(CalAverageofNumbersResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalServiceServer is the server API for CalService service.
type CalServiceServer interface {
	//Unary
	Calculation(context.Context, *CalRequest) (*CalResponse, error)
	//Server Streaming
	PrimeNoDecomposition(*PrimeNoDecompositionRequest, CalService_PrimeNoDecompositionServer) error
	//Client streaming
	CalAverageofNumbers(CalService_CalAverageofNumbersServer) error
}

// UnimplementedCalServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCalServiceServer struct {
}

func (*UnimplementedCalServiceServer) Calculation(context.Context, *CalRequest) (*CalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calculation not implemented")
}
func (*UnimplementedCalServiceServer) PrimeNoDecomposition(*PrimeNoDecompositionRequest, CalService_PrimeNoDecompositionServer) error {
	return status.Errorf(codes.Unimplemented, "method PrimeNoDecomposition not implemented")
}
func (*UnimplementedCalServiceServer) CalAverageofNumbers(CalService_CalAverageofNumbersServer) error {
	return status.Errorf(codes.Unimplemented, "method CalAverageofNumbers not implemented")
}

func RegisterCalServiceServer(s *grpc.Server, srv CalServiceServer) {
	s.RegisterService(&_CalService_serviceDesc, srv)
}

func _CalService_Calculation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalServiceServer).Calculation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalService/Calculation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalServiceServer).Calculation(ctx, req.(*CalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalService_PrimeNoDecomposition_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeNoDecompositionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalServiceServer).PrimeNoDecomposition(m, &calServicePrimeNoDecompositionServer{stream})
}

type CalService_PrimeNoDecompositionServer interface {
	Send(*PrimeNoDecompositionResponse) error
	grpc.ServerStream
}

type calServicePrimeNoDecompositionServer struct {
	grpc.ServerStream
}

func (x *calServicePrimeNoDecompositionServer) Send(m *PrimeNoDecompositionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CalService_CalAverageofNumbers_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalServiceServer).CalAverageofNumbers(&calServiceCalAverageofNumbersServer{stream})
}

type CalService_CalAverageofNumbersServer interface {
	SendAndClose(*CalAverageofNumbersResponse) error
	Recv() (*CalAverageofNumbersRequest, error)
	grpc.ServerStream
}

type calServiceCalAverageofNumbersServer struct {
	grpc.ServerStream
}

func (x *calServiceCalAverageofNumbersServer) SendAndClose(m *CalAverageofNumbersResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calServiceCalAverageofNumbersServer) Recv() (*CalAverageofNumbersRequest, error) {
	m := new(CalAverageofNumbersRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _CalService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalService",
	HandlerType: (*CalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculation",
			Handler:    _CalService_Calculation_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeNoDecomposition",
			Handler:       _CalService_PrimeNoDecomposition_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CalAverageofNumbers",
			Handler:       _CalService_CalAverageofNumbers_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "calculator/calpb/cal.proto",
}
